// Generated by https://quicktype.io

export interface CreateArticleExitDto {
    idPetitioner: number;
    idArea: number;
    idUser: number;
    articleExitDetails: ArticleExitDetail[];
}

export interface ArticleExitDetail {
    idArticle: number;
    amount: number;
}
