// Generated by https://quicktype.io

export interface PetitionerForm {
    petitioner_id:     number;
    petitioner_name:   string;
    petitioner_status: boolean;
    petitioner_areaId: number;
    area_id:           number;
    area_name:         string;
    area_status:       boolean;
}
